### ISSUE TITLE
Please add release tag

### ISSUE THREAD

**Issue by tillea** [danielrmeyer/g2#1]
Hi,
it seems this project was saved from SourceForge where it vanished to Github.  It would help if at least the latest release could be tagged as 0.72.  This would enable pointing the Debian packaging to some valid download tarball.
Kind regards, Andreas.

**Comment by danielrmeyer** [comment]
Just added a release tag.  I'm actually a bit excited this turned out to be useful.  I used this library on a project many years ago and recently needed some simple graphics, but could not find the library on the Internet--so I just hoisted this up here.  Let me know if I can be of any more assistance.  Thanks!
