### ISSUE TITLE
Original Source Repo

### ISSUE THREAD

**Issue by Lewiscowles1986** [danielrmeyer/g2#2]
I Can't seem to find the original source for this repo, the closest I've come is a site with doxygen docs that seem to be here, some notes on the virtual devices

http://www.ncbr.muni.cz/~martinp/g2/index.html

Is this an original Source Repo? If it's not would it be an idea to start a GitHub org, and move it there?

**Comment by danielrmeyer** [comment]
Sorry, I don't know anything about the original repo.  I had the source code since I used this for a project many years ago in grad school.  I noticed I could not find the code anymore so I pushed it up here.  I have nothing to do with the original creators.

I am curious to know if people are using this and I am considering actively maintaining and updating it.  For now I just stuck it here for safe keeping.

**Comment by Lewiscowles1986** [comment]
I only know it exists because element14 mentioned it in an article about C on raspberry pi. 

TBH distro's seem to have a copy (at least debian and ubuntu)

* https://packages.debian.org/sid/libg2-dev
* https://packages.ubuntu.com/xenial/libg2-dev

I'm uncertain what happened to the original author repository. If you'd like to maintain it outside of a distro, I'm sure others would be happy. I know it was on SourceForge, but the link is dead like you've said.

I'll close this out as it was more of a question, than an issue.
